### PR TITLE
Refactoring Bot.js _resolveSkillFromTopicWithConfidence label:hacktoberfest

### PR DESCRIPTION
**Pull request by noodlesegg**
adding JSDoc

### CODE REVIEW

**Comment by manthanhd** [comment]
Hey @noodlesegg these changes look like they are part of a bigger commit? Just checking.

**Comment by noodlesegg** [comment]
Hi @manthanhd just for the hactoberfest :D don't know how to put labels in it

**Comment by manthanhd** [comment]
@noodlesegg Unfortunately I'll have to close this as it is not contributing anything of significant value to the project.

**Comment by manthanhd** [comment]
@noodlesegg I'm sure you'll find something cool to work on from the issues.

**Pull request closed without merging**
